---
title: "Crime"
author: "Barry Bullas MBE"
date: "01/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

list_of_packages <- c("rvest", "dplyr", "lubridate", "plotly")
new_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)

#Load required packages
lapply(list_of_packages, library, character.only = TRUE)

# In Future look at retrieving data via an API or SmarterScotland package

# Load all data
scot_crime <- read.csv('data/crime_stats.csv', stringsAsFactors=FALSE)
area_lookup <- read.csv('data/area_lookup.csv', stringsAsFactors=FALSE)
```

## Scottish Crime Statistics

This project analyses the rate per 10,000 population, of crimes and offences recorded by the police.  The data has been obtained from statistics.gov.scot<https://statistics.gov.scot>.

For more information on the recorded crime figures please see <http://www.scotland.gov.uk/Topics/Statistics/Browse/Crime-Justice/PubRecordedCrime>.

```{r include = FALSE}

# Filter to get only Ratio measurements for All Crimes
scot_all_crime <- scot_crime %>%
    filter (Crime.or.Offence == 'All Crimes' & Measurement == "Ratio" & FeatureCode != 'S92000003') %>%
  mutate(DateCode=dmy(paste('01/01', substr(DateCode, 1, 4))))


  # Get names for Feature Codes
scot_all_crime <-   left_join(scot_all_crime, area_lookup, by = c("FeatureCode" = "FeatureCode"))

```

## All Recorded Crime

```{r echo=FALSE, warning=FALSE}
# Create a plot
p <- plot_ly(scot_all_crime, x = ~DateCode, y = ~Value, color = ~Area) %>%
  layout(title = "All Scottish Crime",
    scene = list(
      xaxis = list(title = "Year"),
      yaxis = list(title = "Rate Per 10,000 Population")))%>%
  add_lines()

  p


```

